[font]
size = 15

[font.normal]
family = "Maple Mono Normal"

[window]
padding = {x = 10}
dynamic_padding = true

[scrolling]
history = 0

[mouse]
hide_when_typing = true

[colors.primary]
background = "#000000"
foreground = "#d5d5d5"

