# Silkpaper light
[colors.primary]
background = "#f0edec"
foreground = "#1a1a1a"

[colors.cursor]
cursor = "#6f657c"
text   = "#f7f3e8"

[colors.normal]
black   = "#1a1a1a"
red     = "#b03030"
green   = "#2e6b3e"
yellow  = "#a05010"
blue    = "#2c4f7a"
magenta = "#7a3868"
cyan    = "#2a6b70"
white   = "#999980"

[colors.bright]
black   = "#555545"
red     = "#cc3535"
green   = "#3a7a4a"
yellow  = "#b85a15"
blue    = "#3a6090"
magenta = "#8f4a82"
cyan    = "#337a80"
white   = "#f7f3e8"
