# Made this (with gentle help of AI) 
# to imitate a blue-green-ish chalkboard.
#
# Based on solarized, but with much more muted colors.

[colors-dark]
background=002b36
foreground=839496

#cursor=002b36 b09a82 # yellow-ish
cursor=002b36 ad8078 # red-pink-ish

# Normal ANSI colors
regular0=073642
regular1=95686b
regular2=718b7e
regular3=92876f
regular4=607f8e
regular5=857487
regular6=668589
regular7=839496

# Bright ANSI colors
bright0=073642
bright1=95686b
bright2=718b7e
bright3=92876f
bright4=607f8e
bright5=857487
bright6=668589
bright7=839496

#selection-background=073642
#selection-foreground=93a1a1
#urls=268bd2
#jump-labels=002b36 b58900
#scrollback-indicator=002b36 2aa198
#search-box-no-match=002b36 dc322f
#search-box-match=002b36 b58900
