# Must be imported after colors.conf due to dependency upon it

bar {
	position bottom
    status_command ~/.config/sway/status.sh
	colors {
	  background $FG
	  statusline $BG_SUBTLE
	  # class		      border	 bg	    	 text
	  focused_workspace   $BG_MUTED  $BG_SUBTLE  $FG
	  inactive_workspace  $FG        $FG   		 $BG_SUBTLE
	  urgent_workspace    $FG  		 $FG 		 #FF5555
	  binding_mode        $FG  		 $FG 		 #FF5555
	}
}
