bar {
	position bottom
    status_command ~/.config/sway/status.sh
	colors {
	  background $FG
	  statusline $BG_SUBTLE
	  # class		      border	bg	    text
	  focused_workspace   $BG_MUTED    $BG_SUBTLE  	$FG
	  inactive_workspace  $FG       $FG   	$BG_SUBTLE
	  urgent_workspace    #FF5555  #FF5555 	#F8F8F2
	  binding_mode        #FF5555  #FF5555 	#F8F8F2
	}
}
