### Color variables
set $FG "24292f"
set $BG "f5f5f5"

set $BG_SUBTLE "d1d5da"
set $BG_MUTED "8a8a8a"

set $URGENT "b03030"

## background
 output * bg #d1d5da solid_color
 
# class                 	border      bg	    	text      indicator c_border
client.focused          	$BG_MUTED   $BG    		$FG    	  $BG_MUTED    $BG_SUBTLE
client.unfocused        	$BG_SUBTLE  $BG_SUBTLE  $BG_MUTED $BG_SUBTLE   $BG
client.focused_inactive 	$BG_MUTED   $BG_SUBTLE  $FG       $BG_SUBTLE   $BG_SUBTLE
#client.urgent           	b03030    	f2eedf    	b03030    b03030       b03030

