general.import = [
	"~/.config/alacritty/theme.toml"
]

[font]
size = 14

[font.normal]
family ="Maple Mono Normal NL"
style = "Regular"

[window]
padding = {x = 10}
dynamic_padding = true

[scrolling]
history = 0

[mouse]
hide_when_typing = true

# Sonokai colors

[colors.primary]
foreground = "#e2e2e3"
background = "#2c2e34"

[colors.normal]
black = "#181819"
red = "#fc5d7c"
green = "#9ed072"
yellow = "#e7c664"
blue = "#76cce0"
magenta = "#b39df3"
cyan = "#f39660"
white = "#e2e2e3"

[colors.bright]
black = "#7f8490"
red = "#fc5d7c"
green = "#9ed072"
yellow = "#e7c664"
blue = "#76cce0"
magenta = "#b39df3"
cyan = "#f39660"
white = "#e2e2e3"

[colors.cursor]
text = "#2c2e34"
cursor = "#e2e2e3"

[colors.selection]
text = "CellForeground"
background = "#414550"
