general.import = [
	"~/.config/alacritty/theme.toml"
]

[font]
size = 16

[font.normal]
family = "Fantasque Sans Mono"
style = "Regular"

[window]
padding = {x = 10}
dynamic_padding = true

[scrolling]
history = 0

[mouse]
hide_when_typing = true

