exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP DBUS_SESSION_BUS_ADDRESS
exec_always export XDG_CURRENT_DESKTOP=sway

### Input settings
input type:keyboard {
   xkb_layout "eu"
   xkb_options caps:escape
}
input type:mouse {
	accel_profile flat
}

seat seat0 xcursor_theme Bibata-Modern-Classic 24
output * scale 1.0

exec_always gammastep -l 51.49:9.14 -t 6500:3000 -b 1.0:0.4

font pango:Recursive Sn Lnr St 10.5

# Utilities:
# Special keys to adjust volume via PulseAudio
bindsym --locked XF86AudioMute exec pactl set-sink-mute \@DEFAULT_SINK@ toggle
bindsym --locked XF86AudioLowerVolume exec pactl set-sink-volume \@DEFAULT_SINK@ -5%
bindsym --locked XF86AudioRaiseVolume exec pactl set-sink-volume \@DEFAULT_SINK@ +5%
bindsym --locked XF86AudioMicMute exec pactl set-source-mute \@DEFAULT_SOURCE@ toggle
# Special keys to adjust brightness via brightnessctl
bindsym --locked XF86MonBrightnessDown exec brightnessctl set 5%-
bindsym --locked XF86MonBrightnessUp exec brightnessctl set 5%+


